<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2022-04-05 18:13:45',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2022-04-14 23:52:30',
                'route' => NULL,
                'parameters' => '',
            ),
            4 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 1,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2018-05-20 21:08:37',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 2,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2018-05-20 21:08:37',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '/admin/compass',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 3,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2018-05-20 21:08:37',
                'route' => NULL,
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'featured' => 1,
                'created_at' => '2017-11-21 16:23:22',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => '#000000',
                'parent_id' => 8,
                'order' => 4,
                'featured' => 1,
                'created_at' => '2018-06-22 20:53:25',
                'updated_at' => '2018-06-22 20:54:13',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Certifications',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-certificate',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'featured' => 1,
                'created_at' => '2022-03-13 07:05:04',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.certifications.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 34,
                'menu_id' => 3,
                'title' => 'Projects',
                'url' => 'My Best Projects',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Project',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'featured' => 1,
                'created_at' => '2022-03-14 06:47:37',
                'updated_at' => '2022-04-21 03:31:50',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 35,
                'menu_id' => 3,
                'title' => '*Social Media',
                'url' => 'Find Me On',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Medium',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'featured' => 1,
                'created_at' => '2022-03-14 06:51:11',
                'updated_at' => '2022-04-17 09:58:33',
                'route' => NULL,
                'parameters' => '',
            ),
            12 => 
            array (
                'id' => 36,
                'menu_id' => 3,
                'title' => 'Certifications',
                'url' => 'Industry Recognized',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Certification',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'featured' => 1,
                'created_at' => '2022-03-14 06:51:55',
                'updated_at' => '2022-04-17 09:58:54',
                'route' => NULL,
                'parameters' => '',
            ),
            13 => 
            array (
                'id' => 37,
                'menu_id' => 3,
                'title' => 'Skills',
                'url' => 'Based on Uxcel Skill Assessment',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Skill',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'featured' => 1,
                'created_at' => '2022-03-14 06:52:42',
                'updated_at' => '2022-04-21 03:31:50',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'featured' => 1,
                'created_at' => '2022-03-15 09:45:01',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.media.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 40,
                'menu_id' => 3,
                'title' => 'Tools',
                'url' => 'Powerful Toolkit',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Tool',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'featured' => 1,
                'created_at' => '2022-03-15 12:39:49',
                'updated_at' => '2022-04-17 09:59:27',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'featured' => 1,
                'created_at' => '2022-03-15 12:43:14',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.tools.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 42,
                'menu_id' => 3,
                'title' => '*Contact Me',
                'url' => 'Just Imagine',
                'target' => '_self',
                'icon_class' => 'contacts',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'featured' => 1,
                'created_at' => '2022-03-15 14:34:32',
                'updated_at' => '2022-04-17 09:59:27',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 43,
                'menu_id' => 1,
                'title' => 'Skills',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pie-chart',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'featured' => 1,
                'created_at' => '2022-03-18 12:59:50',
                'updated_at' => '2022-04-05 18:16:36',
                'route' => 'voyager.skills.index',
                'parameters' => 'null',
            ),
            19 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Projects',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-laptop',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'featured' => 1,
                'created_at' => '2022-03-22 11:50:22',
                'updated_at' => '2022-04-03 12:20:57',
                'route' => 'voyager.projects.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 46,
                'menu_id' => 1,
                'title' => 'Social-Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-facebook',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'featured' => 1,
                'created_at' => '2022-04-02 03:38:51',
                'updated_at' => '2022-04-05 08:02:43',
                'route' => 'voyager.social-media.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 49,
                'menu_id' => 1,
                'title' => 'Sections',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'featured' => 1,
                'created_at' => '2022-04-03 13:10:28',
                'updated_at' => '2022-04-03 13:10:28',
                'route' => 'voyager.menus.builder',
                'parameters' => '{
"menu":"*\\\\$id=($this->model(\'Menu\')->where(\'name\',auth()->user()->username)->exists()?$this->model(\'Menu\')->where(\'name\',auth()->user()->username)->first()->id:1);"
}',
            ),
            22 => 
            array (
                'id' => 50,
                'menu_id' => 5,
                'title' => 'Works',
                'url' => 'recent projects',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Project',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'featured' => 1,
                'created_at' => '2022-04-21 19:42:28',
                'updated_at' => '2022-04-21 19:42:28',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 51,
                'menu_id' => 5,
                'title' => 'Skills',
                'url' => 'my skillset',
                'target' => '_self',
                'icon_class' => '\\App\\Models\\Skill',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'featured' => 1,
                'created_at' => '2022-04-21 19:43:07',
                'updated_at' => '2022-04-21 19:43:07',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 53,
                'menu_id' => 5,
                'title' => '*Contact Me',
                'url' => 'let\'s chat',
                'target' => '_self',
                'icon_class' => 'chat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'featured' => 1,
                'created_at' => '2022-04-21 21:01:36',
                'updated_at' => '2022-04-21 21:01:36',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}